sudo: required

language: java
jdk:
  - openjdk8

node_js:
  - "11"

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - console2/node_modules

install: true
script:
  - mvn install -Pdocker -Pit -B
